### PR TITLE
`PoseSensor` semantic component

### PR DESCRIPTION
**Pull request by RobertWilbrandt**
This PR implements a new semantic components for robots or sensors that can meassure a cartesian pose. I will add a PR for a `pose_broadcaster` controller using this to `ros2_controllers` shortly.

My use-case for this functionality is for robots that can provide their cartesian TCP pose in addition to their normal joint state (e.g. UR and Kuka arms). This can be more accurate than forward kinematics, as the robot can use its factory calibration for determining this pose. In the future, there could also be different kinds of sensors implementing this (e.g. mocap) to allow their data to be used in a controller.

I tried my best to keep the implementation close to the existing fts and imu components. The tests should also cover similar use, in particular loading of the controller and lifecycle transitions as well as verifying a published pose.

### CODE REVIEW

**Review by bmagyar — DISMISSED** [review]
Grand! :ok_hand:

**Review by saikishor — APPROVED** [review]
LGTM

**Review by christophfroehlich — CHANGES_REQUESTED** [review]
LGTM, but please have a look at the failing precommit job.

**Comment by RobertWilbrandt** [comment]
Thanks for the fast review! The pre-commit errors should be fixed now.

**Review by saikishor — CHANGES_REQUESTED** [review]
Can you please add this to the release_notes document?

**Review by christophfroehlich — DISMISSED** [review]

**Review by bmagyar — APPROVED** [review]

**Comment by RobertWilbrandt** [comment]
Sure, i added a line to `release_notes.rst`

**Review by saikishor — APPROVED** [review]
LGTM

**Review by bmagyar — APPROVED** [review]

**Pull request merged**
