### PR TITLE
Fix multiple calls of cleanup when system is unconfigured

### PR DESCRIPTION
**Pull request by destogl**
Replaces #1175

### CODE REVIEW

**Review by bmagyar — APPROVED** [review]

**Review by christophfroehlich — COMMENTED** [review]
Should we also return OK in `PRIMARY_STATE_FINALIZED`? This would maybe fix #1103, see the last point of the instructions in https://github.com/ros-controls/ros2_control_demos/pull/417

**Comment by destogl** [comment]
Oh, yes, will do tomorrow morning. :)

**Review by saikishor — APPROVED** [review]
LGTM. Thank you @destogl. 

One question, why don't we use return type OK by default, but when we enter the INACTIVE and ACTIVE state we set it the ERROR at the beginning after the condition, in such a way we don't have to code OK for every lifecycle state.

(or)

Something as simple as if and else and by default we return OK in else 
```
  if (
    impl_->get_state().id() == lifecycle_msgs::msg::State::PRIMARY_STATE_INACTIVE ||
    impl_->get_state().id() == lifecycle_msgs::msg::State::PRIMARY_STATE_ACTIVE)
  {
    return_type result = impl_->read(time, period);
    if (result == return_type::ERROR)
    {
      error();
    }  
    return result;
  }
  else
  {
    return return_type::OK;
  }
}
```

What do you think?

In any case, the current changes look fine to me. :)

**Comment by destogl** [comment]
@saikishor, I see your point here. This is definitely a simpler code, but I would like to have it rather explicit. Any unplanned thing should end up in error and `OK` state should be set explict.

**Comment by saikishor** [comment]
> @saikishor, I see your point here. This is definitely a simpler code, but I would like to have it rather explicit. Any unplanned thing should end up in error and `OK` state should be set explict.

Make sense. I agree with you. Thanks for the explanation. :+1:

**Review by christophfroehlich — APPROVED** [review]
Now it fixes #1103 too, thanks!

**Pull request merged**
