### PR TITLE
Add test coverage for `params_file` parameter in spawner/unspawner tests

### PR DESCRIPTION
**Pull request by SantoshGovindaraj**
**Overview**
* Solve https://github.com/ros-controls/ros2_control/issues/1702 
* This PR adds test cases for the `params_file` parameter in the test_spawner_unspawner.cpp.

### CODE REVIEW

**Review by christophfroehlich — CHANGES_REQUESTED** [review]
Thanks for your contribution. Please run [pre-commit locally](https://github.com/ros-controls/ros2_control/blob/master/CONTRIBUTING.md#contributing-via-pull-requests) to satisfy the linters.

**Comment by SantoshGovindaraj** [comment]
Thanks @saikishor and @christophfroehlich 

I have fixed the changes as mentioned.

**Comment by saikishor** [comment]
> Thanks @saikishor and @christophfroehlich
> 
> I have fixed the changes as mentioned.

I'm waiting for @christophfroehlich or other maintainers to trigger the CI

**Review by christophfroehlich — APPROVED** [review]
Thanks. I haven't checked if the assertion was added to every test, but it seems to be fine.

**Review by saikishor — APPROVED** [review]
LGTM

**Comment by SantoshGovindaraj** [comment]
Thanks @saikishor and @christophfroehlich for prompt replies. 
Please feel free to let me know if any further changes required, I can amend the changes.

**Review by bmagyar — APPROVED** [review]

**Pull request merged**
