### PR TITLE
Replace random_shuffle with shuffle.

### PR DESCRIPTION
**Pull request by clalancette**
In C++14 and newer, std::random_shuffle is deprecated.  Here, switch to using std::shuffle instead with a random number generator of our choosing.

Contributions via pull requests are much appreciated. Before sending us a pull request, please ensure that:

1. Limited scope. Your PR should do one thing or one set of things. Avoid adding “random fixes” to PRs. Put those on separate PRs.
2. Give your PR a descriptive title. Add a short summary, if required.
3. Make sure the pipeline is green.
4. Don’t be afraid to request reviews from maintainers.
5. New code = new tests. If you are adding new functionality, always make sure to add some tests exercising the code and serving as live documentation of your original intention.

To send us a pull request, please:

- [x] Fork the repository.
- [x] Modify the source; please focus on the specific change you are contributing. If you also reformat all the code, it will be hard for us to focus on your change.
- [x] Ensure local tests pass. (`colcon test` and `pre-commit run` (requires you to install pre-commit by `pip3 install pre-commit`)
- [x] Commit to your fork using clear commit messages.
- [x] Send a pull request, answering any default questions in the pull request interface.
- [x] Pay attention to any automated CI failures reported in the pull request, and stay involved in the conversation.

### CODE REVIEW

**Review by christophfroehlich — APPROVED** [review]
Thanks!

**Review by saikishor — APPROVED** [review]
LGTM

**Comment by clalancette** [comment]
There were 5 failures in CI here:
1. `Coverage Build - Rolling / coverage_rolling / coverage build rolling (pull_request)` - failed because it is not installing `test_msgs`, which is needed to build `realtime_tools`.  Not related to this PR.
1. `Rolling Binary Build / binary (rolling, main) / rolling main (pull_request)` - Failed because it is using too new a version of pycodestyle, and not a new enough version of flake8.  Not related to this PR.
1. `Rolling Semi-Binary Build / binary (rolling, main) / rolling main (pull_request)` - Same problem
1. `Rolling Binary Build / binary (rolling, testing) / rolling testing (pull_request)` - Same problem
1. `Rolling Semi-Binary Build / binary (rolling, testing) / rolling testing (pull_request) ` - Same problem

Thus, I think this PR is good to go if someone wants to merge it and do a release into Rolling.  Thank you!

**Comment by christophfroehlich** [comment]
I agree, they are not related to this PR. 


>     1. `Coverage Build - Rolling / coverage_rolling / coverage build rolling (pull_request)` - failed because it is not installing `test_msgs`, which is needed to build `realtime_tools`.  Not related to this PR.

Strange, why isn't it [installed with rosdep](https://github.com/ros-controls/realtime_tools/blob/master/package.xml#L26)?


>     2. `Rolling Binary Build / binary (rolling, main) / rolling main (pull_request)` - Failed because it is using too new a version of pycodestyle, and not a new enough version of flake8.  Not related to this PR.
> 

https://bugs.launchpad.net/ubuntu/+source/flake8/+bug/2056093

**Review by bmagyar — APPROVED** [review]

**Pull request merged**
