### PR TITLE
Make RHEL CI happy!

### PR DESCRIPTION
**Pull request by VX792**
Possible solution for issue #725

Haven't tested the build on Rhel, but based on the logs the error could be that the variables declared with the auto keyword in the descriptions.hpp file are deducted into initializer lists of `const char*`, and the compiler for some reason couldn't convert them into vectors of `const char*`..

### CODE REVIEW

**Review by erickisos — APPROVED** [review]
👏

**Review by bmagyar — APPROVED** [review]

**Comment by bmagyar** [comment]
:facepalm: because we made it master-only

**Comment by bmagyar** [comment]
Ok @jaron-l  you are right... it's on a PR that was not followed-up on

**Comment by bmagyar** [comment]
ok, someone else please also confirm this but it seems to me that RHEL fails on master but succeeds to build here (don't check the status, look also at the logs pls)

**Comment by jaron-l** [comment]
> ok, someone else please also confirm this but it seems to me that RHEL fails on master but succeeds to build here (don't check the status, look also at the logs pls)

Looks like controller manager is still failing tests. I'll run it locally and post the logs as my RHEL workflow doesn't post the error for some reason.

**Review by destogl — APPROVED** [review]

**Comment by jaron-l** [comment]
> > ok, someone else please also confirm this but it seems to me that RHEL fails on master but succeeds to build here (don't check the status, look also at the logs pls)
> 
> Looks like controller manager is still failing tests. I'll run it locally and post the logs as my RHEL workflow doesn't post the error for some reason.
> 
> But it does build if that's all we care about.

So I think this PR does cause a new test to fail. It's in the `controller_manager` pkg at `test/test_controller_manager_srvs.cpp::TestControllerManagerSrvs.list_controllers_srv`. Here's the failed output:

```
4: /home/src/ros2_control/controller_manager/test/test_controller_manager_srvs.cpp:148: Failur
e
4: Value of: result->controller[0].claimed_interfaces
4: Expected: has 6 elements where
4: element #0 is equal to "joint2/velocity",
4: element #1 is equal to "joint3/velocity",
4: element #2 is equal to "joint2/max_acceleration",
4: element #3 is equal to "configuration/max_tcp_jerk",
4: element #4 is equal to "joint1/position",
4: element #5 is equal to "joint1/max_velocity"
4:   Actual: { "joint1/position", "joint1/max_velocity", "joint2/velocity", "joint3/velocity",
 "joint2/max_acceleration", "configuration/max_tcp_jerk" }, whose element #0 doesn't match
4: [  FAILED  ] TestControllerManagerSrvs.list_controllers_srv (175 ms)
```

Looks like the order of the vector changed.

**Comment by bmagyar** [comment]
Thanks @VX792 for the fix, as we discussed, UnorderedElementsAre fixed the problem!

**Pull request merged**
