### PR TITLE
Remove todo resource checking

### PR DESCRIPTION
**Pull request by v-lopez**
Goes on top of https://github.com/ros-controls/ros2_control/pull/261

### CODE REVIEW

**Comment by destogl** [comment]
@bmagyar can you rebase this to make a review cleaner?

**Comment by bmagyar** [comment]
@destogl done

**Review by bmagyar — APPROVED** [review]
This is fine with me, although some of the methods may be still useful but we don't have robot_hw to tie them to anymore

**Comment by v-lopez** [comment]
Yes, for part of the funcionality I added this: https://github.com/ros-controls/ros2_control/issues/262

**Comment by bmagyar** [comment]
Removing dead code in 3, 2, 1...

**Pull request merged**
