### PR TITLE
Add controller exception handling in controller manager

### PR DESCRIPTION
**Pull request by saikishor**
This PR adds the exception handling in the controller manager for the most commonly used controller methods that are triggered by different controller manager services

### CODE REVIEW

**Review by christophfroehlich — APPROVED** [review]
This is a very much needed feature :grin: 

There would be even more methods of the `controller_interface` to handle, like the `command_interface_configuration` which could also throw exceptions (during development, giving the user some better feedback).

**Comment by christophfroehlich** [comment]
Closes #451

**Comment by saikishor** [comment]
> This is a very much needed feature 😁
> 
> There would be even more methods of the `controller_interface` to handle, like the `command_interface_configuration` which could also throw exceptions (during development, giving the user some better feedback).

Sure, I can take a look. I thought so of adding it, but then as it is only the `InterfaceConfiguration`, which basically has a list and then the enum, that's the reason I didn't add it. The worst that could happen there is a Segmentation fault, which we cannot do anything anyway.
 
The problem is this is present in many lines and I don't know if it is worth it.

**Comment by christophfroehlich** [comment]
Ok i haven't checked the number of calls. Let it as it is..

**Review by bmagyar — APPROVED** [review]
Grand, thank yoU!

**Pull request merged**
