### PR TITLE
Namespace Loaded Controllers

### PR DESCRIPTION
**Pull request by sp-sophia-labs**
## Description

The goal of this PR is to enable namespaces for controller_manager and properly cascade namespace to the loaded controllers 

## How has this been tested?

We have tested this code on create3 and turtlebot4 robots. You can find our project here: https://github.com/sp-sophia-labs/turtlebot4_multi_sim.  Reviewers may clone the project and replicate exactly what we use for testing (you can find the details in the project's README)

## Checklist

- [x] Rebase on master
- [x] Lint code with appropriate parser
- [x] Rebase code on galactic branch

### CODE REVIEW

**Review by destogl — COMMENTED** [review]
I am not sure how I am feeling about ABI braking on EOL distro. We could do it because there will be no releases, but not much value in it.

**Comment by bmagyar** [comment]
@sp-sophia-labs similarly to https://github.com/ros-controls/ros2_controllers/pull/461 please port this over to the `master` branch instead

**Comment by sp-sophia-labs** [comment]
While rebasing on master, I realized that most of my changes were already covered with a significant rework on constructors to include namespaces. I'm leaving this PR with the minimal change that remains

**Review by bmagyar — APPROVED** [review]

**Comment by destogl** [comment]
@mergifyio backport humble

**Pull request merged**
