### PR TITLE
Make list controller and list hardware components immediately visualize the state.

### PR DESCRIPTION
**Pull request by destogl**
1. Colorize the name and state of the hardware component respective to its state.
2. Colorize the controller name according to its state and make the output more tabular for easier reading.

### New output `list_hardware_components`
Screenshot_20240709_110427-1

### New output `list_controllers`
Screenshot_20240705_212755-1

### CODE REVIEW

**Review by saikishor — APPROVED** [review]
Apart from the pre-commit jobs failing, the content itself looks good to me.
Thanks @destogl

**Review by saikishor — APPROVED** [review]
LGTM

**Comment by bmagyar** [comment]
I think we should have something different for `inactive` controllers. Dark green and bright green aren't that different, green suggests it's running...

**Comment by saikishor** [comment]
I believe is CYAN right? How about "Magenta"? :|
image

**Comment by bmagyar** [comment]
Indeed I think magenta would be better

**Review by bmagyar — APPROVED** [review]
amazing!

**Comment by destogl** [comment]
@mergifyio backport humble

**Comment by destogl** [comment]
https://github.com/Mergifyio backport iron

**Pull request merged**
