### PR TITLE
Unused header cleanup

### PR DESCRIPTION
**Pull request by henrygerardmoore**
Follow-on for [my other PR](https://github.com/ros-controls/ros2_controllers/pull/1199), another one just removing unused headers. Also removes some unused `using` declarations, and a test (`test_transmission_parser.cpp`) that wasn't being built and was including a file that was removed a while ago in #633. Also standardizes to use braced includes (e.g. `<gmock/gmock.h>`) as opposed to using quotes for gtest and gmock.

Tests pass locally, no noticeable build time improvements (so this is just a style change). The removed test accounts for the vast majority of the lines removed at 441 lines (don't worry :smile:)

### CODE REVIEW

**Comment by olivier-stasse** [comment]
It looks fine, but before approving the 13 workflows should be approved by one of the maintainers to see what the builders say.

**Review by olivier-stasse — COMMENTED** [review]
It looks fine, but before approving the 13 workflows should be approved by one of the maintainers to see what the builders say.

**Review by christophfroehlich — APPROVED** [review]
Thanks for the cleanup (again!). The failing tests are not related to this PR and already reported.

**Review by saikishor — APPROVED** [review]
Thanks for the cleanup!!

**Review by olivier-stasse — APPROVED** [review]
Thanks

**Review by bmagyar — APPROVED** [review]

**Comment by christophfroehlich** [comment]
@henrygerardmoore @bmagyar Merging this breaks lots of packages in ros2_controllers repo, because there are now missing includes. I fix ros2_controllers, but we might break lots of other downstream packages.

**Comment by henrygerardmoore** [comment]
@christophfroehlich I can make a PR for ros2_control_demos, are there any others that you know of?

**Comment by christophfroehlich** [comment]
> @christophfroehlich I can make a PR for ros2_control_demos, are there any others that you know of?

I created one for ros2_controllers and for ros2_control_demos, the other packages of ros2_control stack build still fine. I only fear the next release on the build farm, but we'll see.

```
apt-cache rdepends ros-rolling-controller-interface
ros-rolling-controller-interface
Reverse Depends:
  ros-rolling-ur-controllers
  ros-rolling-robotiq-controllers
  ros-rolling-picknik-twist-controller
  ros-rolling-picknik-reset-fault-controller
  ros-rolling-canopen-ros2-controllers
```

> apt-cache rdepends ros-rolling-hardware-interface
> ros-rolling-hardware-interface
> Reverse Depends:
>   ros-rolling-ur-robot-driver
>   ros-rolling-topic-based-ros2-control
>   ros-rolling-kortex-driver
>   ros-rolling-dynamixel-hardware
>   ros-rolling-canopen-ros2-controllers
>   ros-rolling-canopen-ros2-control

**Comment by henrygerardmoore** [comment]
Sorry for the trouble, was there a better way I should have gone about the unused header cleanup?

**Comment by christophfroehlich** [comment]
I think that you did a good job, the only easy thing would have been to compile the obvious dependencies (ros2_controllers for example).
Packages not following the "include what you use" paradigm will have problems now, this is fine for rolling now :grin:

**Pull request merged**
