### PR TITLE
Inverse the response of cli commands to return correct exit-status.

### LINKED ISSUE #306: Some cli commands return '1' even through it's successfully executed
Some `ros2 control` commands return exit-status '1' even through it's successfully executed.

# Environments
- OS: Ubuntu 20.04
- ROS: Foxy
- Software Version: latest of master, commit: fb804313a2a7d3992ef58034a369e8558f7f8c57

# To Reproduce

```sh
# Terminal 1
$ ros2 launch ros2_control_demo_robot rrbot_system_position_only.launch.py

# Terminal 2
$ ros2 control list_hardware_interfaces
$ echo $?
0

$ ros2 control load_start_controller joint_state_controller
$ echo $?
1

$ ros2 control load_configure_controller forward_command_controller_position
$ echo $?
1

$ ros2 control switch_controllers --start-controllers forward_command_controller_position 
$ echo $?
1
```

# Expected behavior

The commands return the exit-status '0'.

### PR DESCRIPTION
**Pull request by ShotaAk**
Fix #306 .

### CODE REVIEW

**Review by bmagyar — APPROVED** [review]
good catch, thanks @ShotaAk !

**Comment by destogl** [comment]
@ShotaAk could you also extend this functionality to other verbs also? so that each verb returns success/failure values?

**Comment by ShotaAk** [comment]
@destogl you mean `list*` verbs right?
Since there are no response `ok` in List*.srv files, I will insert `return 0` to each `list` verbs. Is it OK?

**Comment by bmagyar** [comment]
Thanks for the contribution @ShotaAk !

**Pull request merged**
