### PR TITLE
Update controller_interface/include/semantic_components/imu_sensor.hpp on master

### PR DESCRIPTION
**Pull request by flochre**
Same as #889 but on master 
Solving issue #888

### CODE REVIEW

**Review by bmagyar — APPROVED** [review]

**Comment by bmagyar** [comment]
@mergifyio backport to humble

**Review by destogl — APPROVED** [review]
Great catch! Thanks!

**Comment by cwecht** [comment]
@bmagyar I guess it makes sense to backport this patch directly to humble.

**Comment by bmagyar** [comment]
Absolutely! @mergifyio backport to humble

**Comment by bmagyar** [comment]
Oh wait, it was already backported!:D my job is done here

**Pull request merged**
