### PR TITLE
added conditioning to have rolling tags compilable in older versions

### PR DESCRIPTION
**Pull request by saikishor**
As discussed in the yesterday's WG meeting, I've added some small fixes that will enable us to compile rolling tags directly in earlier versions from now on.

The following are the breaking changes between both versions:
* https://github.com/ros2/rclcpp/commit/9d2849cb0ada510073dc90d7497aa2380a97b51a (The [new API of the NodeOptions](https://github.com/ros2/rclcpp/commit/3610b68348adbc441f130e058f8a8e38032e855a) is available from the tag 21.0.0)
* https://github.com/ros2/rclcpp/commit/4744fb6f500cbb3d7a0619f4ef6a7bdf34370e34 (The [new method of the create client](https://github.com/ros2/rclcpp/commit/64e4c72791811e25ee7780fc84b07dc70f36a4c9) is available from the tag 17.0.0)

### CODE REVIEW

**Review by christophfroehlich — DISMISSED** [review]
LGTM, compiles on humble.
After merge we could add a scheduled CI job for ros-controls:master on ROS humble to ros2_control_ci @fmauch?

**Comment by fmauch** [comment]
> LGTM, compiles on humble. After merge we could add a scheduled CI job for ros-controls:master on ROS humble to ros2_control_ci @fmauch?

Sure we could do that :-)

**Review by fmauch — APPROVED** [review]

**Comment by saikishor** [comment]
> Just one more thing. Could youi please add a distinctive comment about those IFs being there to support source-compatibility with Humble? Same line in both files

Sure, I can do that!

**Comment by saikishor** [comment]
@bmagyar Done :+1:

**Review by bmagyar — APPROVED** [review]
thanks!

**Pull request merged**
