### PR TITLE
Add Support for SDF

### LINKED ISSUE #632: Use ros2 control with sdf model
hi , i am trying to use ros2 control for a parallel robot , and my model is sdf format.
when i want to launch a  project , controller manager needs robot description. but sdf format has no any robot tag.
even i tried to pass my project world and sdf format to controller manager, but it doesn't  work too.

would anybody mind Is ros2 control works with sdf format? 
 how can I handle it?

### PR DESCRIPTION
**Pull request by Amronos**
Fixes #632
I have modified `hardware_interface/src/component_parser.cpp` to add support for SDF models.

To test this out the demos being added through https://github.com/ros-controls/gz_ros2_control/pull/427 can be used.

### CODE REVIEW

**Review by saikishor — CHANGES_REQUESTED** [review]
Can you please add a test with an example SDF here: https://github.com/ros-controls/ros2_control/blob/master/hardware_interface/test/test_component_parser.cpp?

**Review by saikishor — CHANGES_REQUESTED** [review]
@Amronos The changes look good to me. Can you add that SDF parsing is also supported through robot_description topic?. You can add it to the release_notes.rst

Sorry for not pointing out earlier

**Review by saikishor — APPROVED** [review]
LGTM

**Comment by azeey** [comment]
This is great! Thanks @Amronos

**Comment by Amronos** [comment]
Are there any updates on when this PR can be reviewed and merged?

**Comment by Amronos** [comment]
The test `successfully_parse_valid_sdf` is passing for me when running `colcon test`, but failing in the GitHub checks. Any idea why this is the case?

**Comment by bmagyar** [comment]
Do you have a non-standard URDF library installed? The CI errors come from this segment
```
  // parse full URDF for mimic options
  urdf::Model model;
  if (!model.initString(urdf))
  {
    throw std::runtime_error("Failed to parse URDF file");
}
```
located here https://github.com/ros-controls/ros2_control/pull/1763/files#diff-ae927ba56161377a082def3ca0417c1052c37949d94e27a7713e3f9f798e790eR853
and the other print comes directly from within the `initString()` call from [here](https://github.com/ros/urdfdom/blob/master/urdf_parser/src/model.cpp#L107)

Seems legit to me but I'm wondering how it worked for you :D

**Comment by Amronos** [comment]
> Do you have a non-standard URDF library installed?

I don't have a non-standard URDF library installed and the test is passing for me.
I did try rebuilding with colcon and testing multiple times. I also tried re-cloning the repo.
Is it possible that something in the CI is outdated?

**Comment by christophfroehlich** [comment]
> Is it possible that something in the CI is outdated?

I don't think so, it fails on debian, RHEL and ubuntu

**Comment by Amronos** [comment]
https://github.com/ros-controls/gz_ros2_control/pull/427 should help in testing this PR.

**Comment by azeey** [comment]
I've locally verified that the test fails because the `ros-<distro>-sdformat-urdf` package is not installed. One option is to add `sdformat_urdf` to the `package.xml`. @christophfroehlich / @bmagyar is that something you'd be okay with?

**Comment by Amronos** [comment]
Oh, that explains it. Thanks a lot @azeey!

**Comment by azeey** [comment]
IIUC, the Source and Semi-Binary builds do not install dependencies based on the package.xml in the PR, but use a docker image built from the `master` branch. Should the `sdformat_urdf` repo be added to https://github.com/ros-controls/ros2_control/blob/master/ros2_control.jazzy.repos and https://github.com/ros-controls/ros2_control/blob/master/ros2_control.rolling.repos?

**Comment by christophfroehlich** [comment]
@azeey @Amronos I realized that [sdformat_urdf](https://index.ros.org/search/?term=sdformat_urdf&section=pkgs) is not released for distros older than jazzy. We try to make the rolling branch compilable on humble as well, so I see the following options:
- release sdformat_urdf for humble ;)
- is it compilable on humble from source? could you provide a repos file for that? then I can add it to the compatibility build's repos file. (would be helpful for the debian images anyways).
- if it is not compilable, could you please include macros for automatically disabling sdf-support if ros2_control is compiled on humble?

**Comment by azeey** [comment]
@christophfroehlich not sure why index.ros.org is not picking it up, but I can see `ros-humble-sdformat-urdf` is available (see http://packages.ros.org/ros2/ubuntu/pool/main/r/ros-humble-sdformat-urdf/).

**Comment by azeey** [comment]
Releases into RHEL pending: https://github.com/ros/rosdistro/pull/43303, https://github.com/ros/rosdistro/pull/43304

**Comment by christophfroehlich** [comment]
I am confused. Debian and RHEL are compiling fine now, but the test fail on these systems. What could be different here compared to the ubuntu jobs?

**Comment by azeey** [comment]
@christophfroehlich in https://github.com/ros-controls/ros2_debian/pull/11, even though `sdformat_urdf` was added to the .repos file, looking at the build logs shows that it was not built. Taking a closer look, I see that the set of packages to be built in the docker image is set in 
https://github.com/ros-controls/ros2_debian/blob/ecfe2c5d801e0521f21402c3d8c88704df381c18/Dockerfile.debian12#L137-L144

and
https://github.com/ros-controls/ros2_debian/blob/ecfe2c5d801e0521f21402c3d8c88704df381c18/Dockerfile.debian11#L137-L144

but I don't see `sdformat_urdf` in there.

**Comment by christophfroehlich** [comment]
@azeey you are totally right, and same on RHEL
> `dnf: Failed to detect successful installation of [ros-jazzy-sdformat-urdf]`
I was on the wrong track again, because it compiles but behaves differently during runtime.

the gz_tools_vendor are merged but [failed to build](https://build.ros2.org/job/Jbin_rhel_el964__gz_tools_vendor__rhel_9_x86_64__binary/) and [sdformat_urdf](https://build.ros2.org/job/Jsrc_el9__sdformat_urdf__rhel_9__source/) still deactivated.

**Comment by azeey** [comment]
> the gz_tools_vendor are merged but [failed to build](https://build.ros2.org/job/Jbin_rhel_el964__gz_tools_vendor__rhel_9_x86_64__binary/) and [sdformat_urdf](https://build.ros2.org/job/Jsrc_el9__sdformat_urdf__rhel_9__source/) still deactivated.

It looks like an issue with the build infrastructure. I'm working with @cottsay to get it resolved.

**Comment by christophfroehlich** [comment]
> It looks like an issue with the build infrastructure. I'm working with @cottsay to get it resolved.

https://build.ros2.org/job/Jbin_rhel_el964__sdformat_vendor__rhel_9_x86_64__binary/
https://build.ros2.org/job/Rbin_rhel_el964__sdformat_vendor__rhel_9_x86_64__binary/

it seems this fails because tinyxml was not installed for urdf_parser as part of urdfdom
```
07:24:44 DEBUG: /usr/include/urdf_parser/urdf_parser.h:44:10: fatal error: tinyxml.h: No such file or directory
07:24:44 DEBUG:    44 | #include <tinyxml.h>
07:24:44 DEBUG:       |          ^~~~~~~~~~~
```

maybe not related to infrastructure, but only a missing dependency on rhel?

**Review by bmagyar — APPROVED** [review]
Thanks to all involved for pushing this!

**Comment by cottsay** [comment]
The infrastructure issue was resolved, the build failure you're seeing now is legitimate.

> maybe not related to infrastructure, but only a missing dependency on rhel?

Seems like a bug in sdformat or the rosdep rules at first glance. The CMakeLists.txt finds `tinyxml2`, but `tinyxml.h` is provided by `tinyxml` (not 2). There completely separate packages.

**Comment by cottsay** [comment]
Ohh, wait - the include is referenced from the `urdfdom-devel` system package.

That's a missing dependency from the system package. I'll try to get it fixed upstream.

**Comment by azeey** [comment]
The version of liburdfdom-dev in Ubuntu is 4.0.0 whereas in RHEL, it is 1.0.4, so there seems to be a significant difference. I'm not sure what the timeline would be to get the update upstream, so I'll do the the alternative thing and use the `urdfdom` package from packages.ros.org in sdformat_vendor.

**Comment by cottsay** [comment]
> I'm not sure what the timeline would be to get the update upstream

The same ABI stability we rely on to keep our builds turning over is the source of friction for getting this package updated. It's possible, but intentionally difficult to make such a large jump within a RHEL major.

Here's the update to `urdfdom` in RHEL 9: https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2024-2c516e302e

We can work around the problem in the rosdep DB until the update goes stable next week, but it will require re-blooming to take the new rule. If you think that urdfdom 1.0.4 is likely to work and you don't want to wait until next week, I can start that process.

**Comment by azeey** [comment]
@cottsay and I spoke offline and agreed that using the ROS package `urdfdom` is the best option. New releases of sdformat_vendor are on their way:

- https://github.com/ros/rosdistro/pull/43363
- https://github.com/ros/rosdistro/pull/43362

**Comment by saikishor** [comment]
@azeey Thank you for following up. Once these PRs are merged, we can trigger the CI.

I see that these are released to Rolling and Jazzy. Out of curiosity, with the Humble version of `sdformat_urdf` these tests are going to fail or would they work?. 

We are making sure when the rolling is compiled from the source, it is compatible on Humble. That's the reason, I'm asking this question.

**Comment by azeey** [comment]
> I see that these are released to Rolling and Jazzy. Out of curiosity, with the Humble version of sdformat_urdf these tests are going to fail or would they work?.

We've changed how Gazebo packages (e.g. sdformat) are released into ROS in Jazzy, that's why these releases are necessary. For Humble, `sdformat_urdf` should work fine on Ubuntu without any of these changes. I'm not sure about RHEL though. Do you in RHEL for the rolling/humble compatibility?

**Comment by saikishor** [comment]
> We've changed how Gazebo packages (e.g. sdformat) are released into ROS in Jazzy, that's why these releases are necessary. For Humble, `sdformat_urdf` should work fine on Ubuntu without any of these changes. I'm not sure about RHEL though. Do you in RHEL for the rolling/humble compatibility?

For now, mainly focusing on the Ubuntu part. @christophfroehlich am I right?

**Comment by christophfroehlich** [comment]
> For now, mainly focusing on the Ubuntu part. @christophfroehlich am I right?

We have only Ubuntu CI jobs for that. But I'm personally interested in having this running on Debian (I use that in my main project). But if its compilable from source, then everything fine.

**Comment by Amronos** [comment]
Can the checks be run again? I think they should pass now.
Thanks a lot everyone for all the help!

**Comment by azeey** [comment]
RHEL is ✅  🎉 

I'm not sure why the Jazzy and Rolling Binary Build checks are failing. The error messages don't seem related to this PR.

**Review by saikishor — APPROVED** [review]
LGTM

**Pull request merged**
