### PR TITLE
Add an argument to define controller manager timeout

### PR DESCRIPTION
**Pull request by lukicdarkoo**
We are running some "heavy" simulations and it takes more than 10s for our `ros2_control` plugin to load

### CODE REVIEW

**Review by Karsten1987 — APPROVED** [review]

**Comment by lukicdarkoo** [comment]
@Karsten1987 I fixed the linter error, it is passing all controller_manager tests locally. 

BTW, is there a way to avoid `First-time contributors need a maintainer to approve running workflows.`?

**Comment by bmagyar** [comment]
There's currently no opt-out option but apparently [they protect us from you](https://github.blog/2021-04-22-github-actions-update-helping-maintainers-combat-bad-actors/#github-actions-cryptomining-abuse) **mining bitcoin** on our CI :D

**Comment by Karsten1987** [comment]
That kinda confused me, too. I actually don't know where this comes from. @bmagyar do you know what's going on there?

**Review by bmagyar — APPROVED** [review]

**Comment by bmagyar** [comment]
Well apparently someone were mining some sweet crypto in hijacked GH actions. Ingenious!

Also, I'll be merging this so let's welcome @lukicdarkoo to the **Circle of Trust TM**, may your CI jobs be ever-green ;)

**Pull request merged**
