### PR TITLE
Removing 'auto' from function definition to support pre c++ 20

### PR DESCRIPTION
**Pull request by bailaC**

### CODE REVIEW

**Comment by bailaC** [comment]
@bmagyar  please take a look.

**Review by destogl — APPROVED** [review]
Thanks!

**Comment by bmagyar** [comment]
@wmmc88 could you please check if this is satisfactory on your end?

**Review by wmmc88 — APPROVED** [review]
Resolves the warning  in CI and I've confirmed its resolved my issue in windows compile issue!

**Review by bmagyar — APPROVED** [review]
Thanks!

**Pull request merged**
