### PR TITLE
Install spawner/unspawner using console_script entrypoint

### LINKED ISSUE #605: spawner/unspawner cannot be run directly on windows
**Describe the bug**
The spawner executable in the controller_manager package cannot be run on windows.

**To Reproduce**
Several related issues:

Using spawner.py works but you get a deprecation warning:
```
❯ ros2 run controller_manager spawner.py joint_state_broadcaster --controller-manager /controller_manager
C:\Users\melvi\git-repos\ros2_upstream_ws\install\lib\controller_manager\spawner.py:204: DeprecationWarning: 'spawner.py' is deprecated, please use 'spawner' (without .py extension)
  warnings.warn(
```

Using spawner directly results in a conflict in ros2run:
```
❯ ros2 run controller_manager spawner joint_state_broadcaster --controller-manager /controller_manager
Multiple executables found:
- C:\Users\melvi\git-repos\ros2_upstream_ws\install\lib\controller_manager\spawner
- C:\Users\melvi\git-repos\ros2_upstream_ws\install\lib\controller_manager\spawner.py
```

launching spawner from ros2launch using the following snippet fails:
```
joint_state_broadcaster_spawner := Node(
        package="controller_manager",
        executable="spawner",
        arguments=["joint_state_broadcaster", "--controller-manager", "/controller_manager"],
    )
```
```
[ERROR] [spawner.PY-3]: exception occurred while executing process:
Traceback (most recent call last):
  File "C:\dev\ros2_rolling\install\Lib\site-packages\launch\actions\execute_local.py", line 540, in __execute_process
    transport, self._subprocess_protocol = await async_execute_process(
  File "C:\dev\ros2_rolling\install\Lib\site-packages\osrf_pycommon\process_utils\async_execute_process_asyncio\impl.py", line 139, in async_execute_process
    transport, protocol = await _async_execute_process_nopty(
  File "C:\dev\ros2_rolling\install\Lib\site-packages\osrf_pycommon\process_utils\async_execute_process_asyncio\impl.py", line 45, in _async_execute_process_nopty
    transport, protocol = await loop.subprocess_exec(
  File "C:\python38\lib\asyncio\base_events.py", line 1630, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\python38\lib\asyncio\windows_events.py", line 389, in _make_subprocess_transport
    transp = _WindowsSubprocessTransport(self, protocol, args, shell,
  File "C:\python38\lib\asyncio\base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "C:\python38\lib\asyncio\windows_events.py", line 885, in _start
    self._proc = windows_utils.Popen(
  File "C:\python38\lib\asyncio\windows_utils.py", line 153, in __init__
    super().__init__(args, stdin=stdin_rfd, stdout=stdout_wfd,
  File "C:\python38\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\python38\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 is not a valid Win32 application
```

**Expected behavior**
Spawner is launcher without errors or warnings

**Environment (please complete the following information):**
 - OS: Windows
 - Version: master
- Anything that may be unusual about your environment

**Additional context**
The issue looks like its because the spawner script is using a shebang which isn't properly supported in windows. If the desired behaviour is to be able to use `spawner` instead of the deprecated `spawner.py`, the script should be installed as a `console_script` using `ament_python_install_package`. Changes needed to do this would be similar to https://github.com/ros/xacro/pull/304

### PR DESCRIPTION
**Pull request by wmmc88**
fixes #605

### CODE REVIEW

**Comment by wmmc88** [comment]
builds failing because the backported feature hasn't been released yet.

Feature: [May 10 2021](https://github.com/ament/ament_cmake/pull/328)
Galactic Backport: [Dec 7 2021](https://github.com/ament/ament_cmake/pull/364)
Latest Ament_cmake release: [Oct 29 2021](https://github.com/ament/ament_cmake/tags)

**Comment by bmagyar** [comment]
https://github.com/ament/ament_cmake/issues/373

**Comment by destogl** [comment]
@wmmc88 it seems you missed some argument:
```
  CMake Error at /opt/ros/galactic/share/ament_cmake_python/cmake/ament_python_install_package.cmake:39 (message):
    ament_python_install_package() called with unused arguments:
    SCRIPTS_DESTINATION;lib/controller_manager
  Call Stack (most recent call first):
    /opt/ros/galactic/share/ament_cmake_python/cmake/ament_python_install_package.cmake:33 (_ament_cmake_python_install_package)
    CMakeLists.txt:156 (ament_python_install_package)
```

**Comment by wmmc88** [comment]
> @wmmc88 it seems you missed some argument:
> ```
>   CMake Error at /opt/ros/galactic/share/ament_cmake_python/cmake/ament_python_install_package.cmake:39 (message):
>     ament_python_install_package() called with unused arguments:
>     SCRIPTS_DESTINATION;lib/controller_manager
>   Call Stack (most recent call first):
>     /opt/ros/galactic/share/ament_cmake_python/cmake/ament_python_install_package.cmake:33 (_ament_cmake_python_install_package)
>     CMakeLists.txt:156 (ament_python_install_package)
> ```

That doesn't fail once ament_cmake releases to galactic. It's a new arg that was added a while ago

**Comment by destogl** [comment]
> That doesn't fail once ament_cmake releases to galactic. It's a new arg that was added a while ago

OK, then we just have to wait.

**Comment by bmagyar** [comment]
The release was made, we only need to wait for the next sync with this

**Review by destogl — APPROVED** [review]
@bmagyar I am approving this so we can simply retrigger CI and merge this (tomorrow).

**Comment by wmmc88** [comment]
> @bmagyar I am approving this so we can simply retrigger CI and merge this (tomorrow).

I think last Friday was only a rolling sync. Idk when the next galactic sync is but there hasn't been one since 12-27-21. Next foxy sync is 2-8-22 (https://discourse.ros.org/t/preparing-for-foxy-sync-and-patch-release-2022-02-08/24050)  so maybe soon?

**Comment by wmmc88** [comment]
Looks like galactic was just synced:
https://discourse.ros.org/t/preparing-for-galactic-sync-2022-02-09/24176/4?u=wmmc88

**Comment by wmmc88** [comment]
All ci passes after sync!

**Review by bmagyar — APPROVED** [review]

**Pull request merged**
