### PR TITLE
Update ros2_control_node.cpp

### PR DESCRIPTION
**Pull request by ObeidHaidar**

### CODE REVIEW

**Comment by ObeidHaidar** [comment]
Had similar issues to what's described in #859. 

There could be a better way to solve this, but this works on both simulated and real machines.

**Review by ufrhaidar — APPROVED** [review]

**Review by ufrhaidar — APPROVED** [review]

**Review by seanng-1 — APPROVED** [review]

**Comment by olivier-stasse** [comment]
Dear @ObeidHaidar could you elaborate a bit on the test you did in simulation ?
Having heavy controllers to test and complex dynamics to simulate, will this modification works on simulation where you assume that simulation takes no CPU power ?

**Comment by destogl** [comment]
@ObeidHaidar which kind of simulation are you using? This not shouldn't be used in simulation at all. The simulation is setting time there not the node.

**Review by NisharnSP — APPROVED** [review]

**Comment by destogl** [comment]
ping @ObeidHaidar can you refer to the qustions?

**Comment by ObeidHaidar** [comment]
Will keep applying the fix locally.

**Pull request closed without merging**
