### PR TITLE
Replace controller_interface::return_type SUCCESS by OK and mark SUCCESS as deprecated

### LINKED ISSUE #151: Unify return_type nomenclature in hardware_interface and controller_interface
I propose the name change to keep the same nomenclature as for `hardware_interfaces`. What do you think?

```suggestion
  return controller_interface::return_type::OK;
```

_Originally posted by @destogl in https://github.com/ros-controls/ros2_control/pull/139#discussion_r489326777_

hardware_interface uses `OK` and controller_interface uses `SUCCESS`

### PR DESCRIPTION
**Pull request by mateus-amarante**
As per the title.

Fix #151

### CODE REVIEW

**Review by bmagyar — APPROVED** [review]

**Comment by bmagyar** [comment]
Thanks for this fix!

**Comment by Karsten1987** [comment]
I don't quite think this is an API/ABI compatible change. In fact it produced quite a few warnings on the build farm: https://build.ros2.org/job/Fdev__ros2_control__ubuntu_focal_amd64/48/gcc/new/folder.1246564846/

I propose to revert this change and table it for Galactic.

**Comment by bmagyar** [comment]
AFAIK this is an API/ABI compatible change and the warnings produced are the exact deprecation warnings we added. I'll create a follow-up PR to fix the ones highlighted, thanks!

**Comment by Karsten1987** [comment]
Clang is issuing a c++17 warning:
```
error: attributes on an enumerator declaration are a C++17 extension [-Werror,-Wc++17-extensions]
```

**Comment by bmagyar** [comment]
Late to the party

**Pull request merged**
