### PR TITLE
Update build for Eloquent

### PR DESCRIPTION
**Pull request by piraka9011**
This PR applies the same update for Dashing in #19 to the Eloquent branch.

Signed-off-by: Anas Abou Allaban <aabouallaban@pm.me>

### CODE REVIEW

**Comment by Karsten1987** [comment]
I think the dashing updates should land first and the eloquent branch should be forked based on that. I currently don't really see the point why that eloquent exists in the first place, but that's maybe material for a different issue.

**Comment by piraka9011** [comment]
> I think the dashing updates should land first and the eloquent branch should be forked based on that. I currently don't really see the point why that eloquent exists in the first place, but that's maybe material for a different issue.

I agree, if you merge your PR I can start working off of that. 
I also think there should be a `master` branch for latest changes and also a branch for Foxy (since that's what we're targeting).

**Comment by Karsten1987** [comment]
I agree, there should be a `ros2` or `ros2-devel` branch. But as long as we don't break API there is no immediate need to branch off.

**Comment by piraka9011** [comment]
Closing in favor of #19

**Pull request closed without merging**
