### PR TITLE
Adjust controller_manager library destination

### PR DESCRIPTION
**Pull request by bmagyar**

### CODE REVIEW

**Comment by destogl** [comment]
with this changes I get the following error:
```
Package 'controller_manager' exports the library 'controller_manager' which
  couldn't be found
```

The PR is related to #172

**Comment by Karsten1987** [comment]
I don't think there's anything to change here. The install directory is correct for this target.

**Comment by destogl** [comment]
And what about export?

Should we there prefix ${PROJECT_NAME}?

**Comment by Karsten1987** [comment]
> And what about export?

starting with Foxy, we can rely on modern cmake within ament. I wouldn't bother with this right now and could see this as a follow up PR which addresses this altogether on all repositories.

**Comment by bmagyar** [comment]
agreed

**Pull request closed without merging**
