### PR TITLE
Add .gitignore for ros, python, c++

### PR DESCRIPTION
**Pull request by jonatanolofsson**

### CODE REVIEW

**Comment by bmagyar** [comment]
I'm generally not in favour of adding such files to repositories.

**Comment by jonatanolofsson** [comment]
@bmagyar Is there a particular reason why a gitignore shouldn't be checked in? 

The reason was mainly to ignore the __pycache__ directories generated in the ros2controlcli directories, but I've also never heard anything but that having a .gitignore is good practice

**Comment by destogl** [comment]
If we are adding then please only to ignore python cache files. This is very specific and overblown file for the repo.

Although honestly I think we don't need one.

**Comment by Karsten1987** [comment]
I'd second @destogl comment here. Please limit the file to the cases which actually apply here.

**Pull request closed without merging**
