### PR TITLE
Fix controllers parameters of controller manager

### PR DESCRIPTION
**Pull request by delihus**
The issue is described here https://github.com/ros-controls/ros2_control/issues/1506.

### CODE REVIEW

**Review by christophfroehlich — CHANGES_REQUESTED** [review]
Thanks for opening a PR. Do you think you could add a test into `test_spawner_unspawner.cpp` for your usecase?

**Review by saikishor — CHANGES_REQUESTED** [review]
Hello @delihus!

Thanks for the pull request and mainly for reporting the issue. Looking at your reported issue, I personally think that the issue is not in the `spawner`, but it is inside the `controller_manager` code. It is not handling the namespaces very nicely. You can fix it over there or I can fix it in the upcoming days. 
Let us know.

**Review by saikishor — CHANGES_REQUESTED** [review]
@delihus I've reviewed again probably your approach is fine, one more thing why do you have to run your spawner with the same namespace again?

```
python3 spawner.py  joint_trajectory_controller -c controller_manager --controller-manager-timeout 10 --namespace panther --param-file /tmp/jtc.yaml --ros-args -r __ns:=/panther -p use_sim_time:=True
```

I think in the spawner you would also need to change this part `controller_manager_name` to also include the namespace, so this way you might avoid parsing the namespace again via `__ns` right?

https://github.com/ros-controls/ros2_control/blob/9f1007b0bffc13f7eb2e755369dd24302d2db7d1/controller_manager/controller_manager/spawner.py#L351-L353

ideally, it should look something like this right?

```
python3 spawner.py  joint_trajectory_controller -c controller_manager --controller-manager-timeout 10 --namespace panther --param-file /tmp/jtc.yaml --ros-args -p use_sim_time:=True
```

**Comment by delihus** [comment]
> @delihus I've reviewed again probably your approach is fine, one more thing why do you have to run your spawner with the same namespace again?
> 
> ```
> python3 spawner.py  joint_trajectory_controller -c controller_manager --controller-manager-timeout 10 --namespace panther --param-file /tmp/jtc.yaml --ros-args -r __ns:=/panther -p use_sim_time:=True
> ```
Gives:
```bash
[ruby $(which ign) gazebo-1] [ERROR] [1716541010.983187571] [panther.controller_manager]: The 'type' param was not defined for 'joint_trajectory_controller'.
```

> 
> I think in the spawner you would also need to change this part `controller_manager_name` to also include the namespace, so this way you might avoid parsing the namespace again via `__ns` right?
> 
> https://github.com/ros-controls/ros2_control/blob/9f1007b0bffc13f7eb2e755369dd24302d2db7d1/controller_manager/controller_manager/spawner.py#L351-L353
> 
> ideally, it should look something like this right?
>



> ```
> python3 spawner.py  joint_trajectory_controller -c controller_manager --controller-manager-timeout 10 --namespace panther --param-file /tmp/jtc.yaml --ros-args -p use_sim_time:=True
> ```

This gives:
```bash
ros2 run controller_manager  spawner  joint_trajectory_controller -c controller_manager --controller-manager-timeout 10 --namespace panther --param-file /tmp/tmpt7hc4zwy --ros-args -p use_sim_time:=True
[INFO] [1716540758.743235940] [spawner_joint_trajectory_controller]: Waiting for '/controller_manager' node to exist
```

**Comment by anath93** [comment]
@christophfroehlich @delihus For spawner to load namespaced controller correctly, try defining in your .yaml file like below to expose this while launching your controller manager

image

then this, 

image

**Comment by saikishor** [comment]
> This gives:
> 
> ```shell
> ros2 run controller_manager  spawner  joint_trajectory_controller -c controller_manager --controller-manager-timeout 10 --namespace panther --param-file /tmp/tmpt7hc4zwy --ros-args -p use_sim_time:=True
> [INFO] [1716540758.743235940] [spawner_joint_trajectory_controller]: Waiting for '/controller_manager' node to exist
> ```

@delihus Could you let me know if you made the changes to this part of the code to include the namespace?

https://github.com/ros-controls/ros2_control/blob/9f1007b0bffc13f7eb2e755369dd24302d2db7d1/controller_manager/controller_manager/spawner.py#L351-L353

Because if you do it, then it should wait for the namespace node right?

**Comment by anath93** [comment]
> > This gives:
> > ```shell
> > ros2 run controller_manager  spawner  joint_trajectory_controller -c controller_manager --controller-manager-timeout 10 --namespace panther --param-file /tmp/tmpt7hc4zwy --ros-args -p use_sim_time:=True
> > [INFO] [1716540758.743235940] [spawner_joint_trajectory_controller]: Waiting for '/controller_manager' node to exist
> > ```
> 
> @delihus Could you let me know if you made the changes to this part of the code to include the namespace?
> 
> https://github.com/ros-controls/ros2_control/blob/9f1007b0bffc13f7eb2e755369dd24302d2db7d1/controller_manager/controller_manager/spawner.py#L351-L353
> 
> Because if you do it, then it should wait for the namespace node right?

@saikishor Did you namespace the controller manger in node side like this ?

image

**Comment by saikishor** [comment]
> @saikishor Did you namespace the controller manger in node side like this ?
> 
> image

@delihus I know that you namespace it like that, but what I mean is that the in the below code if you in the node_name, instead of parsing the  `controller_manager_name` pass already the namespaced one like `controller_namespace + "/" + controller_manager_name` and see if it works instead of having to namespace the spawner again with `__ns`. What do you say?

https://github.com/ros-controls/ros2_control/blob/9f1007b0bffc13f7eb2e755369dd24302d2db7d1/controller_manager/controller_manager/spawner.py#L351-L353

**Comment by delihus** [comment]
> > @saikishor Did you namespace the controller manger in node side like this ?
> > image
> 
> @delihus I know that you namespace it like that, but what I mean is that the in the below code if you in the node_name, instead of parsing the `controller_manager_name` pass already the namespaced one like `controller_namespace + "/" + controller_manager_name` and see if it works instead of having to namespace the spawner again with `__ns`. What do you say?
> 
> https://github.com/ros-controls/ros2_control/blob/9f1007b0bffc13f7eb2e755369dd24302d2db7d1/controller_manager/controller_manager/spawner.py#L351-L353

Yeah, you're right this worked:

```python

    initial_joint_controller_spawner_started = Node(
        package="controller_manager",
        executable="spawner",
        arguments=[

            [device_namespace, "_joint_trajectory_controller"],
            "-t",
            "joint_trajectory_controller/JointTrajectoryController",
            "-c",
            [robot_namespace, "/controller_manager"],
            "--controller-manager-timeout",
            "10",
            "--param-file",
            namespaced_initial_joint_controllers_path,
        ],
    )
```
`ros2 topic list`:

```
/panther/ur3e_joint_trajectory_controller/controller_state
/panther/ur3e_joint_trajectory_controller/joint_trajectory
/panther/ur3e_joint_trajectory_controller/state
/panther/ur3e_joint_trajectory_controller/transition_event
```

**Review by saikishor — CHANGES_REQUESTED** [review]
@delihus Could you add a test for this use-case?

**Pull request closed without merging**
