### PR TITLE
Fixes of issue with seg-fault when checking interfaces on unconfigured controllers.

### PR DESCRIPTION
**Pull request by destogl**
+ small restructuring of helper functions.

### CODE REVIEW

**Comment by bmagyar** [comment]
still looks like a valid idea to me tbh

**Comment by destogl** [comment]
@mergify rebase master

**Review by progtologist — CHANGES_REQUESTED** [review]
LGTM overall.
Commits should be squashed before merging as 8ec4533f552caf752ae1778f1a83e806cda3dcdd and 2f99065e5a8c00020add44dbfbbf4b3d88ec2658 are cancelling each other out.

**Comment by destogl** [comment]
> LGTM overall. Commits should be squashed before merging as [8ec4533](https://github.com/ros-controls/ros2_control/commit/8ec4533f552caf752ae1778f1a83e806cda3dcdd) and [2f99065](https://github.com/ros-controls/ros2_control/commit/2f99065e5a8c00020add44dbfbbf4b3d88ec2658) are cancelling each other out.

Thanks for the observation. We are always squashing commits. This enables us to have a clear history. 
This means that we don't have to squash anything on the PR. So if you are happy, please make this approved.

P.S. should we add a comment about this in the reviewers' manual?

**Review by progtologist — APPROVED** [review]

**Review by homalozoa — APPROVED** [review]

**Review by Serafadam — APPROVED** [review]

**Review by bmagyar — APPROVED** [review]
Thanks!

**Comment by bmagyar** [comment]
@mergifyio backport to galactic

**Pull request merged**
