### PR TITLE
Use namespace in controller_manager

### PR DESCRIPTION
**Pull request by jonatanolofsson**
Add missing namespace parameter to allow controller_manager to be namespaced

### CODE REVIEW

**Review by Karsten1987 — APPROVED** [review]
makes a lot of sense. thanks for the contribution.

**Comment by jonatanolofsson** [comment]
Happy to help!

**Comment by cco-seasony** [comment]
Hey @jonatanolofsson , 
Thanks for the contribution. I have a question regarding the usage of the namespace. What would be the best way to define the namespace in the controller_manager yaml file?
I have been trying a few things but I do not manage to make it work. Any suggestions are more than welcome.
Thanks in advance!

**Comment by jonatanolofsson** [comment]
@cco-seasony Namespaces should be defined in your launch-file, as the structure of your configuration-file depends on the namespace your node is in.

**Comment by cco-seasony** [comment]
@jonatanolofsson Thanks for your reply. The issue is that I am using the gazebo_ros2_control plugin where the config file is parsed in the urdf-file of the robot as a parameter. I already have everything set up with my desired namespace in the launch files but I cannot manage to give a namespace to the controller_manager inside when using it in the gazebo_ros2 _control plugin.

**Comment by jonatanolofsson** [comment]
@cco-seasony For the case of gazebo_ros2_control, you may be interested in my PR: https://github.com/ros-simulation/gazebo_ros2_control/pull/80

**Comment by cco-seasony** [comment]
@jonatanolofsson amazing, that is exactly what I needed. Thanks! I will follow the PR.

**Pull request merged**
