### PR TITLE
Add error message if ros2controlcli commands fail

### PR DESCRIPTION
**Pull request by v-lopez**

### CODE REVIEW

**Comment by destogl** [comment]
@v-lopez what do you think about #308? do you have any idea how to combine it with this PR?

**Comment by v-lopez** [comment]
#308 is right, I assumed the return value was ignored, but it had to be negated. 

I still like the error messages added here, we could add to #308, but I don't know what's the standard practice. ros2param doesn't use exceptions, but ros2service does.

**Comment by destogl** [comment]
@bmagyar what do you think? which way to go?

**Comment by bmagyar** [comment]
Yeah I think the error messages are valuable but we should pass the return values as done in #308 . That one is ready to merge so let's rework this on top of that

**Comment by v-lopez** [comment]
Done, feel free to take a look.

**Review by bmagyar — APPROVED** [review]

**Pull request merged**
