### PR TITLE
simple transmission configure multiple definition fix

### PR DESCRIPTION
**Pull request by niiquaye**

### CODE REVIEW

**Comment by bmagyar** [comment]
Could you please explain what this fixes? What error were you getting and on what system?

**Comment by bmagyar** [comment]
ping @niiquaye

**Comment by niiquaye** [comment]
```
/usr/bin/ld: CMakeFiles/uwrt_mars_rover_drivetrain_hw.dir/src/uwrt_mars_rover_drivetrain_hw_real.cpp.o: in function `transmission_interface::SimpleTransmission::configure(std::vector<transmission_interface::JointHandle, std::allocator<transmission_interface::JointHandle> > const&, std::vector<transmission_interface::ActuatorHandle, std::allocator<transmission_interface::ActuatorHandle> > const&)':
uwrt_mars_rover_drivetrain_hw_real.cpp:(.text+0x20): multiple definition of `transmission_interface::SimpleTransmission::configure(std::vector<transmission_interface::JointHandle, std::allocator<transmission_interface::JointHandle> > const&, std::vector<transmission_interface::ActuatorHandle, std::allocator<transmission_interface::ActuatorHandle> > const&)'; CMakeFiles/uwrt_mars_rover_drivetrain_hw.dir/src/uwrt_mars_rover_drivetrain_hw.cpp.o:uwrt_mars_rover_drivetrain_hw.cpp:(.text+0x20): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/uwrt_mars_rover_drivetrain_hw.dir/build.make:217: libuwrt_mars_rover_drivetrain_hw.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:78: CMakeFiles/uwrt_mars_rover_drivetrain_hw.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
---
--- stderr: uwrt_mars_rover_drivetrain_hw
/usr/bin/ld: CMakeFiles/uwrt_mars_rover_drivetrain_hw.dir/src/uwrt_mars_rover_drivetrain_hw_real.cpp.o: in function `transmission_interface::SimpleTransmission::configure(std::vector<transmission_interface::JointHandle, std::allocator<transmission_interface::JointHandle> > const&, std::vector<transmission_interface::ActuatorHandle, std::allocator<transmission_interface::ActuatorHandle> > const&)':
uwrt_mars_rover_drivetrain_hw_real.cpp:(.text+0x20): multiple definition of `transmission_interface::SimpleTransmission::configure(std::vector<transmission_interface::JointHandle, std::allocator<transmission_interface::JointHandle> > const&, std::vector<transmission_interface::ActuatorHandle, std::allocator<transmission_interface::ActuatorHandle> > const&)'; CMakeFiles/uwrt_mars_rover_drivetrain_hw.dir/src/uwrt_mars_rover_drivetrain_hw.cpp.o:uwrt_mars_rover_drivetrain_hw.cpp:(.text+0x20): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/uwrt_mars_rover_drivetrain_hw.dir/build.make:217: libuwrt_mars_rover_drivetrain_hw.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:78: CMakeFiles/uwrt_mars_rover_drivetrain_hw.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

**Comment by destogl** [comment]
@niiquaye if your code somewhere publicly available? This is probably the "usage" issue.

**Comment by wmmc88** [comment]
> @niiquaye if your code somewhere publicly available? This is probably the "usage" issue.

I don't see how this is a usage issue. The problem here is that the configure function is defined in the simple_transmission header file. So when you `#include transmission_interface/simple_transmission.hpp` in more than one translation unit (ie. Cpp file) then you end up with multiple definitions of the function at link time.

**Comment by bmagyar** [comment]
Ok, thanks. Let's merge this and I may revise the API/file setup for rolling

**Review by bmagyar — APPROVED** [review]

**Comment by bmagyar** [comment]
@mergify backport foxy

**Pull request merged**
