### PR TITLE
move resource manager to hardware interface

### PR DESCRIPTION
**Pull request by Karsten1987**
sits on top of #224 

given the discussion in #216, I've moved the resource manager to a public API which essentially gets passed in to the controller manager instead of the robot hardware instance.

I've further had to move the resource manager into the hardware interface package, as I had circular dependency between controller manager and controller interface if not.
This PR is not changing any code, simply moving files around.

### CODE REVIEW

**Review by bmagyar — APPROVED** [review]
nice!

**Comment by bmagyar** [comment]
If you can get this to compile we could merge it into #224

**Comment by bmagyar** [comment]
@Karsten1987 the build should be fixed

**Comment by Karsten1987** [comment]
I'll merge this into #224 as this will make sense in order to address your outstanding comments on that PR.

**Pull request merged**
