### PR TITLE
Do not use CLI calls but direct API for setting parameters.

### PR DESCRIPTION
**Pull request by destogl**
This PR avoids usage of CLI calls that caused issues with many controllers on some DDS implemenations (FastDDS).
The problem is checks done at the begining of CLI commands that expect that nodes are immediatelly visible.

Now spawner is using API which is generally better and also more robust.

This works great. There is only one small "issue" - `load_param_file` method does not return anything (will submit PR upstream)

### For the reference you can check here what we were using and what we are using now:

**Load parameters file**
- [CLI (old)](https://github.com/ros2/ros2cli/blob/rolling/ros2param/ros2param/verb/load.py)
- [ros2param.api (new)](https://github.com/ros2/ros2cli/blob/rolling/ros2param/ros2param/api/__init__.py#L43)

**Set parameter (controller type)**
- [CLI (old)](https://github.com/ros2/ros2cli/blob/rolling/ros2param/ros2param/verb/set.py)
- [ros2param.api (new)](https://github.com/ros2/ros2cli/blob/rolling/ros2param/ros2param/verb/set.py#L59-L78)

### CODE REVIEW

**Review by bmagyar — DISMISSED** [review]
Just s quick check: none of the newly referenced libraries require a new packagexml entry right? It's all standard rclpy baggage?

**Comment by destogl** [comment]
> Just s quick check: none of the newly referenced libraries require a new packagexml entry right? It's all standard rclpy baggage?

CI seems to be happy, but to be 100% sure I have added a few more deps.

**Comment by destogl** [comment]
> > Just s quick check: none of the newly referenced libraries require a new packagexml entry right? It's all standard rclpy baggage?
> 
> CI seems to be happy, but to be 100% sure I have added a few more deps.

Only `rcl_interfaces` are missing. Those are added implicitly, but let's make this explicit :D

**Comment by destogl** [comment]
OK, maybe is this too old for label to work. We will test in the next rebased PR.

**Comment by destogl** [comment]
@mergifyio backport humble

**Pull request merged**
