### PR TITLE
Pass Down Command Data From An Arbitrary ROS2 Controller To The Hardware Interface

### PR DESCRIPTION
**Pull request by swiz23**
Adds desired feature from https://github.com/ros-controls/ros2_controllers/issues/568

### CODE REVIEW

**Comment by bmagyar** [comment]
I understand you probably need this in humble but please retarget the PR to the master branch. Once that's merged, we can consider backporting.

**Comment by swiz23** [comment]
Will do

**Comment by bmagyar** [comment]
Thank you!

**Comment by swiz23** [comment]
Closing this PR in favor of the one that's merging into 'master' instead of 'humble'

**Pull request closed without merging**
